
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Test

on: [push, pull_request]

jobs:
  Grouping:
    runs-on: ubuntu-latest

    steps:

    # - name: Git Checkout
    #   uses: actions/checkout@v2

    - name: Test
      run: |
        echo "Outside group"
        echo "Outside group"
        echo "::group::My title"
        echo "Inside group"
        echo "Inside group"
        echo "Inside group"
        echo "::group::Another group"
        echo "Inside group 2"
        echo "Inside group 2"
        echo "::group::Yet Another group"
        echo "Inside group 3"
        echo "Inside group 3"
        echo "::endgroup::"
        echo "::endgroup::"
        echo "::endgroup::"
        echo "Outside group"
        echo "Outside group"

